// SCROLL DOWN TO THE "ACTUAL MAP FORMAT STUFF" SECTION
// it is where you should make changes, when tuning this
// script for a new game

/*************************************/
/**           UTILITY FUNCS         **/
/*************************************/

// prefix a string with copies of a character
function prefixChars(s, char, count) {
    var prefix = "";
    for (var i = 0; i < count; i++) {
        prefix += char;
    }
    return prefix + s;
}

// take a value and turn it into a Lua-encoded form
function toLua(value, pretty=false, indent=4, indentChar=" ", currentIndent=0) {
    if (typeof value === "number" || typeof value === "string") {
        // numbers and strings, close enough to JSON so just use JSON
        return JSON.stringify(value);
    } else if (typeof value === "undefined" || value === null) {
        // nil is our answer to null and undefined
        return "nil";
    } else if (typeof value === "object") {
        if (Array.isArray(value)) {
            // Arrays use curly braces in Lua
            return (pretty ? "{\n" : "{") +
                value.map(v => prefixChars(toLua(v, pretty, indent, indentChar, currentIndent + indent), indentChar, pretty ? currentIndent + indent : 0)).join(pretty ? ",\n" : ",")  +
            (pretty ? "\n" + prefixChars("}", indentChar, pretty ? currentIndent : 0) : "}");
        } else {
            // Objects use equal sign instead of colon
            var a = [];
            for (let prop of Object.keys(value)) {
                a.push(prefixChars(prop + "=" + toLua(value[prop], pretty, indent, indentChar, currentIndent + indent), indentChar, pretty ? currentIndent + indent : 0));
            }
            return (pretty ? "{\n" : "{") + a.join(pretty ? ",\n" : ",") + (pretty ? "\n" + prefixChars("}", indentChar, pretty ? currentIndent : 0) : "}");
        }
    }

    return "nil";
}

/**********************************************/
/**         ACTUAL MAP FORMAT STUFF          **/
/**  Modify below as needed for the specific **/
/**  love2d game you are working on. Every   **/
/**  game will probably differ here.         **/
/**********************************************/

var customMapFormat = {
    name: "Custom Lua map format",
    extension: "luamap",
    
    // API docs for the "map" variable are at
    // https://www.mapeditor.org/docs/scripting/classes/TileMap.html
    //
    // Cheatsheet:
    //  - map.layers is an Array of Layer
    //  - Useful fields/methods in Layer:
    //    - name
    //    - isTileLayer()
    //    - isObjectLayer()
    //    - isImageLayer()
    //  - TileLayer:
    //    - width      as in number of tiles
    //    - height     as in number of tiles
    //    - cellAt(x, y) returns a cell, which has tileId, flippedHorizontally, empty, etc.
    //    - tileAt(x, y) returns a Tile or null if empty
    //  - ObjectGroup: << Note, "Group" not "Layer" unlike above
    //    - objects is an Array of MapObject
    //  - MapObject:
    //    - name
    //    - resolvedProperty("key")
    //    - x
    //    - y
    //    - tileFlippedHorizontally
    //    - rotation
    //  - ImageLayer:
    //    - imageFileName
    //    - opacity
    //    - repeatX    is a boolean
    //    - repeatY    is a boolean
    //    - parallaxFactor.x, parallaxFactor.y
    //    - tintColor
    //    - offset.x, offset.y
    //  
    write: function(map, fileName) {
        var f = new TextFile(fileName, TextFile.WriteOnly);
        f.write("-- This file is generated by another program. Don't edit this\n");
        f.write("-- directly or else your changes might get overwritten!\n");
        f.write("return ");
        f.write(toLua({
        }, true));
        f.write("\n");
        f.commit();
    },
    
    // read: function(fileName) {
    // },
    
    // Optional. Returns the list of files that will be written
    // upon export. Use this only if write() needs to write to several files.
    // outputFiles: function(map, fileName) {
    // }
};
tiled.registerMapFormat("customlua", customMapFormat);
